requirements.txt
langchain remove base class of embedding in v0.0.293, so temporarily set langchain version <=0.0.292
=> [fix] requirement.txt

apps/agentfabric/app.py, apps/agentfabric/config/model_config.json, apps/agentfabric/publish_util.py
1. remove openai  gpt3.5 and gpt4 temperaily
2. rename qwen dashscope api to qwen-api
3. fix knowledge file path error for published agent
=> adjust create configure and fix knowledge file path error for published agent

MANIFEST.in
fix code interpreter error when installed from whl,  the error is as follows
```bash
[2023-12-10 19:37:32] To disable this warning, you can either:
[2023-12-10 19:37:32]     - Avoid using `tokenizers` before the fork if possible
[2023-12-10 19:37:32]     - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
[2023-12-10 19:37:32] INFO: kernel process's PID = 7943
[2023-12-10 19:37:36] ---------------------------------------------------------------------------
[2023-12-10 19:37:36] FileNotFoundError                         Traceback (most recent call last)
[2023-12-10 19:37:36] Cell In[1], line 50
[2023-12-10 19:37:36]      47 sns.set_theme()
[2023-12-10 19:37:36]      49 _m6_font_prop = FontProperties(fname='/opt/conda/lib/python3.8/site-packages/modelscope_agent/t …
```
=> add missing files for font

apps/agentfabric/app.py
目前更新config不会触发reset builder（只触发更新builder配置）。因此builder agent的组件prompt不会被更新。因此 切换中英文时，builder不会跟着切换。
修改：更新builder config时，re-init builder
=> fix: reset builder

modelscope_agent/action_parser_factory.py, modelscope_agent/constant.py, modelscope_agent/prompt/prompt_factory.py
将mapping的映射由 str: str 转为 str: cls。 原因：如果类名变换，后者能检查出来，前者不能
=> fix mapping

apps/agentfabric/config/model_config.json, apps/agentfabric/user_core.py, modelscope_agent/agent.py, modelscope_agent/agents/role_play.py, modelscope_agent/llm/__init__.py, modelscope_agent/llm/base.py, modelscope_agent/llm/dashscope.py, modelscope_agent/llm/zhipu.py, modelscope_agent/tools/amap_weather.py
=> Zhipu-glm4

modelscope_agent/agent.py
1. [functions_with_chat_models for openai api](https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models) 
2. 在父类 Agent 中 _detect_tool 添加解析 openai 接口返回的 function name 和 argument
=> update agent _detect_tool compatible with openai api

.dev_scripts/dockerci.sh
=> ffmpeg download stuck, temporarily bypass

apps/agentfabric/app.py, modelscope_agent/memory/base.py, tests/test_agent.py, tests/ut_utils.py, tests/utils/test_token_count.py
在memory类中，增加了token counting的逻辑。token count会随着每一次的`memory.update_history`进行更新。增加了此feature后，可以在AgentFabric中灵活调用`memory.get_token_count`接口，获取token的消耗总量。
fix #341
=> add token counting logic (#341)

modelscope_agent/agents/role_play.py, modelscope_agent/llm/base.py, modelscope_agent/llm/dashscope.py, modelscope_agent/llm/ollama.py, modelscope_agent/llm/openai.py, modelscope_agent_servers/README.md, modelscope_agent_servers/assistant_server/api.py, modelscope_agent_servers/assistant_server/models.py, modelscope_agent_servers/assistant_server/utils.py, scripts/run_assistant_server.sh
1. test result for qwen-max in dashscope
2. test result for llama3 in ollama 
3. test result for openai gpt3.5
=> openai compatible chat api

scripts/run_assistant_server.sh
When run scripts/run_assistant_server.sh, all the cmd line parameters will be passed to vllm as long as --model is passed. So that parameters of vllm could be passed freely. Someone else could help to extend this idea.
=> Pass parameters freely to scripts/run_assistant_server.sh

scripts/run_assistant_server.sh
=> update modelscope-server setting

modelscope_agent/llm/base.py, modelscope_agent/llm/dashscope.py, modelscope_agent/llm/ollama.py, modelscope_agent/llm/openai.py, tests/test_callback.py
When calling the `OpenAi` class's `_chat_no_stream()` method, the `usage_info` result is empty. Upon investigation, the issue was identified in the `stat_last_call_token_info` method. Since this method uses `yield`, it turns into a generator function and does not execute correctly within `_chat_no_stream()`, causing `usage_info` not to be updated properly.
When calling the llm with no stream, `usage_info` is empty:
```python
from modelscope_agent.llm import get_chat_model
msg = [ {"role": "user", "content": 'hello'} ]
llm = get_chat_model(**llm_config)
resp = llm.chat(messages=msg,
max_tokens=1024,
temperature=1.0,
stream=False)
usage_info = llm.get_usage()
```
```python
>>> usage_info = {}
```
```python
>>> usage_info = {'prompt_tokens': 5, 'completion_tokens': 10, 'total_tokens': 15} …
```
=> Fix bug in `_chat_no_stream` to ensure `usage_info` is updated correctly

.dev_scripts/dockerci.sh, .github/workflows/citest.yaml, apps/agentfabric/requirements.txt, requirements.txt
=> pass citest for unknown reason from moviepy

modelscope_agent/llm/__init__.py, modelscope_agent/llm/openai.py
Support Azure openai, reference [here](https://learn.microsoft.com/zh-cn/azure/ai-services/openai/chatgpt-quickstart?tabs=command-line%2Cpython-new&pivots=programming-language-python)
#243
Please review @zzhangpurdue
=> support AZure Openai

apps/agentfabric/server.py, modelscope_agent/tools/utils/openapi_utils.py, requirements.txt
=> better openapi resolver

.github/workflows/publish.yaml, apps/mcp-playground/env.py, apps/mcp-playground/tools/oss.py, apps/mcp-playground/ui_components/add_mcp_server_button.py, modelscope_agent/tools/base.py, modelscope_agent/tools/mcp/mcp_client.py, modelscope_agent/tools/mcp/servers/crawl4ai/README.md, modelscope_agent/tools/mcp/servers/crawl4ai/config.json, modelscope_agent/tools/mcp/servers/crawl4ai/requirements.txt, modelscope_agent/tools/mcp/servers/crawl4ai/server.py, setup.py, test_single.py
1. Add crawl4ai for build-in mcp server
2. Recover mcp playground code
=> Merge release/0.8 to master

modelscope_agent/schemas.py
- Fixed TypeError where Plan.replace_task() was called with 3 arguments instead of 2.
- Adjusted task replacement logic to ensure correct parameter passing.
reference: https://github.com/modelscope/ms-agent/issues/650
fix #650
=> Bug fix 650: handle incorrect argument count in Plan.replace_task

ms_agent/rag/extraction_manager.py, ms_agent/rag/optimized_extraction.py, ms_agent/workflow/research_workflow.py
1. Add ray support for accelerating hierarchical keyInformation information extraction.
2. Add conditional Ray import with serial fallback when Ray is unavailable.
3. Add multi-level fallback to serial logic when actor execution fails.
4. Support CPU allocation and worker count control.
=> add ray support for accelerating document information extraction

ms_agent/agent/base.py, ms_agent/llm/anthropic_llm.py, ms_agent/llm/model_mapping.py, ms_agent/llm/openai_llm.py, ms_agent/utils/__init__.py, tests/llm/test_anthropic.py
=> feat: anthropic llm
