modelscope/ms-agent

config/.env.template, config/cfg_tool_template.json, modelscope_agent/tools/tool.py
1. use one ms token for remote call of all ms-related tools.
=> [feat] use ms tokens for tool remote call

modelscope_agent/llm/ms_gpt.py
migrate msgpt to dashscope service.
1. generate
2. stream generate
=> [feat] use ds token/service for ms gpt

modelscope_agent/llm/__init__.py, modelscope_agent/output_wrapper.py, modelscope_agent/retrieve.py, modelscope_agent/tools/text_to_speech_tool.py
add import in llm.__init__  for load in agentexecutor
=> [fix] fix llm load bugs

demo/demo_qwen_agent.ipynb, demo/demo_retrieval_agent.ipynb
=> [feat] update demo

demo/demo_retrieval_agent.ipynb, requirements.txt
=> fix demo style

modelscope_agent/agent.py, modelscope_agent/tools/tool.py
=> [fix] add remote error handler

demo/tool_agent_finetune_swift/utils/dataset.py
=> add eod token

apps/agentfabric/user_core.py, modelscope_agent/retrieve.py
update to https://modelscope.cn/models/damo/nlp_gte_sentence-embedding_chinese-base/summary
=> update text embedding to damo/nlp_gte_sentence-embedding_chinese-base

apps/agentfabric/app.py, apps/agentfabric/assets/app.css, apps/agentfabric/assets/appBot.css, apps/agentfabric/gradio_utils.py
- 支持拼接成跳转到 fork 创空间的地址，携带上构建好的配置文件地址自动填充
=> feat: support publish navigation

apps/agentfabric/custom_prompt.py, modelscope_agent/tools/code_interpreter_jupyter.py
- modify code interpreter tool description
=> fix: code interpreter tool description

apps/agentfabric/config/model_config.json, apps/agentfabric/user_core.py
set default top_p=0.8, rm top_k=1; set top_p=0.5 during role-play
=> change config

apps/agentfabric/app.py, apps/agentfabric/config/tool_config.json, apps/agentfabric/user_core.py, config/cfg_tool_template.json, modelscope_agent/agent.py
initialization of unused tool is required and rename 配置选项 to OpenAPI Configuration
=> fix: tool init bug and refine UI

modelscope_agent/action_parser.py, modelscope_agent/action_parser_factory.py, modelscope_agent/prompt/prompt_factory.py
prompt & parser的功能与logger同时开发，目前已都合入。修改prompt & parser适配到logger
=> fix: prompt & parser  logger 

apps/agentfabric/app.py, apps/agentfabric/i18n.py
=> refine ui for import config

apps/agentfabric/app.py, apps/agentfabric/builder_core.py, apps/agentfabric/user_core.py
prompt和parser的注册从app.py 改到user core和builder core。
=> fix appBot.py

apps/agentfabric/i18n.py
=> feat: add Bing web search API

apps/agentfabric/appBot.py, apps/agentfabric/publish_util.py
1. check whether tool is selected and then add the token required to env
2. when init error, throw exception and display error in appBot
=> add  key warning

apps/agentfabric/config/builder_config.json, apps/agentfabric/config/builder_config_ci.json, apps/agentfabric/config/builder_config_template.json, apps/agentfabric/config/builder_config_wuxia.json, apps/agentfabric/config/model_config.json, config/cfg_model_template.json
=> update qwen-max -> qwen-max-1201

modelscope_agent/tools/__init__.py, modelscope_agent/tools/dashscope_tools/qwen_vl.py, modelscope_agent/tools/dashscope_tools/wordart_tool.py, tests/tools/test_image_gen.py, tests/tools/test_local_tools.py, tests/tools/test_modelscope_tools.py, tests/tools/test_pipeline_tool.py, tests/tools/test_qwen_vl_tool.py, tests/tools/test_style_repaint.py, tests/tools/test_wordart_tool.py
=> update dashscope_tool:qwen_vl,wordart, to new version

apps/agentfabric/config/tool_config.json, modelscope_agent/tools/__init__.py, modelscope_agent/tools/phantom_tool.py, tests/tools/test_phantom.py
add a new feature named phantom (image enhancement) to the agent
=> add new feature phantom

modelscope_agent/tools/dashscope_tools/sambert_tts_tool.py
=> fix tts for agentfabric

modelscope_agent/agents/role_play.py
修复了https://github.com/modelscope/modelscope-agent/issues/315 中反馈的报错，在_detect_tool函数之前添加了类型判断
=> Add new feature for issue #315

modelscope_agent/llm/dashscope.py
=> feat: qwen1.5

apps/agentfabric/builder_core.py, apps/agentfabric/config/model_config.json, modelscope_agent/agent.py, modelscope_agent/llm/dashscope.py, modelscope_agent/storage/vector_storage.py, modelscope_agent/tools/openapi_plugin.py
1. qwen api return no exceed 6000 limits tokens
2. builder response error while running failed, instead of stucking
3. delete all the tools' instance as well while garbage-collecting the agent
4. fix openapi plugin while no apikey setting
=> bugs fixed

modelscope_agent/multi_agents_tasks/multi_role_videogen_demo.ipynb
=> add demo notebook

README_CN.md
=> Issues fix #353, change README_CN

README.md, README_CN.md, demo/demo_local_new_tool.ipynb, requirements.txt
Add demo about local tool, and change requirements about modelscope version
=> Add demo about local tool, fix #360

demo/demo_alpha_umi.ipynb, modelscope_agent/agents/alpha_umi.py
add a check for importing vllm when running alpha-umi demo
=> [please review]add a check for importing vllm when running alpha-umi demo

demo/demo_history_agent.ipynb
Add demo about memory history, fix #353
=> Add demo about memory history ,fix #353

demo/demo_llamaindex.ipynb
Add demo about use llama_index in modelscope-agent,fix #380
=> Add demo about use llama_index in modelscope-agent,fix #380

README.md, README_CN.md
=> 修改两个文档引用问题

docs/get_started/quickstart.md, docs/modules/memory.md, docs/modules/tool.md
Doc for agent about tool_EN, quickstart_EN and memory_EN,fix #395
=> Doc for agent about tool_EN, quickstart_EN and memory_EN,fix #395

.github/workflows/publish.yaml
=> update pypi publish workflow

demo/demo_openapi_new_tool.ipynb
add demo about openapi with tool,fix #408
=> add demo about openapi with tool,fix #408

examples/llms/ollama.ipynb, modelscope_agent/agents/role_play.py, modelscope_agent/llm/__init__.py, modelscope_agent/llm/ollama.py, requirements.txt
=> feat: ollama

apps/agentfabric/server.py
[issues#425](https://github.com/modelscope/modelscope-agent/issues/425)
=> Add log for bug about openai api config save fail,fix #425

README.md, README_CN.md, modelscope_agent/agent.py, modelscope_agent/agents/role_play.py, modelscope_agent/llm/openai.py, tests/test_agent.py
The test cases:
The origin images:
=> openai multi-modal compatible

modelscope_agent/agent.py, modelscope_agent/tools/base.py
=> fix tool import bugs

modelscope_agent/rag/knowledge.py
=> fix: install nltk data

modelscope_agent/tools/hf_tool.py
=> hotfix transformers version 4.41

.github/workflows/citest.yaml, tests/agents/test_agent_builder.py, tests/tools/test_dashscope_asr_tts.py, tests/tools/test_image_enhancement.py, tests/tools/test_image_gen.py, tests/tools/test_modelscope_tool.py, tests/tools/test_qwen_vl_tool.py, tests/tools/test_style_repaint.py, tests/tools/test_weather.py, tests/tools/test_web_search.py, tests/tools/test_wordart_tool.py
=> allow_fork_pass_ci

modelscope_agent/agent.py, tests/tools/test_openapi_schema.py
fix openapi error in 0.5.0-0.5.2 version
=> Issues#450

docs/training_llms/train_agentfabric_llm_tool_use_cn.md
Fix bug in document of train_agentfabric_llm_tool_use_cn.md 
fix #460
=> fix bug in document of train_agentfabric_llm_tool_use_cn

modelscope_agent/tools/dashscope_tools/image_generation.py, tests/tools/test_image_gen.py, tests/tools/test_image_gen_lite.py
add parameter of image_gen tool，The purpose is to enable the image_gen tool to support the functionality of Lora
=> add parameter of image_gen tool, fix #464

modelscope_agent_servers/README.md
=> fix readme bug

examples/llms/vllm_glm4.ipynb, modelscope_agent/llm/__init__.py, modelscope_agent/llm/openai.py, modelscope_agent/llm/vllm.py, requirements.txt
=> add vllm in LLM module

modelscope_agent/llm/dashscope.py
=> fix none total token

scripts/run_assistant_server.sh
fix model_server conflict in mentioned in this [issue](https://github.com/modelscope/modelscope-agent/issues/482)
=> fix model_server conflict

apps/mobile_agent/run.py, apps/multi_roles_chat_room/role_core.py, docs/modules/tool.md, modelscope_agent/agents/__init__.py, modelscope_agent/environment/__init__.py
=> remove complicated import which might lead import error

modelscope_agent/llm/ollama.py
fix bug about ollama._types.ResponseError: pull model manifest: file does not exist
=> Add error throwing for the Ollama section regarding the download section,fix#487

tests/test_rag.py
=> fix ci: skip if forked

apps/agentfabric/app.py, apps/agentfabric/appBot.py, apps/agentfabric/requirements.txt
fit agentfabric gradio version with tool hub
=> agentfabric gradio setting with tool hub

modelscope_agent/rag/knowledge.py
fix get_extra_readers() return None.
=> bugfix: fix get_extra_readers() return None.

modelscope_agent/rag/knowledge.py, tests/samples/code.py
=> hotfix: rm useless test file & add vector_stores for multiple stores

modelscope_agent/tools/web_search/search_util.py, modelscope_agent/tools/web_search/web_search.py
web search accept token in runtime
=> update web search in order to allow run time verify tokens

README.md, README_CN.md, requirements.txt
=> update requirements and readme

modelscope_agent/tools/dashscope_tools/sambert_tts_tool.py, modelscope_agent/tools/modelscope_tools/text_to_speech_tool.py, modelscope_agent/tools/utils/output_wrapper.py, tests/tools/test_modelscope_tool.py
=> update audio output

scripts/run_tool_node.sh
=> run_tool_node.sh indent error

modelscope_agent/tools/dashscope_tools/paraformer_asr_tool.py, modelscope_agent/tools/dashscope_tools/sambert_tts_tool.py, requirements.txt
=> update ds version

requirements.txt
=> fix llama_index bm25 version

modelscope_agent/llm/dashscope.py
=> fix dashscope llm service stat_last_call_token_info bug

modelscope_agent/agents/data_science_assistant.py, modelscope_agent/tools/code_interpreter/code_interpreter.py
=> Feature/datascience assistant: adding update task logic

modelscope_agent/tools/modelscope_tools/text_to_video_tool.py, modelscope_agent/tools/utils/output_wrapper.py, modelscope_agent_servers/requirements.txt, modelscope_agent_servers/tool_node_server/utils.py, tests/tools/test_dashscope_asr_tts.py, tests/tools/test_modelscope_tool.py
update output wrapper for video to support oss
=> update output wrapper

modelscope_agent/tools/dashscope_tools/paraformer_asr_tool.py, modelscope_agent/tools/dashscope_tools/qwen_vl.py, modelscope_agent/tools/dashscope_tools/style_repaint.py
fix bugs during tool calling cross service
=> fix tool calling error

docs/source/llms/llama3.1_tool_calling.md, docs/source_en/llms/llama3.1_tool_calling.md
add llama3.1  tool calling example
=> support llama3.1 example

modelscope_agent/agent.py, modelscope_agent/tools/base.py, modelscope_agent/tools/langchain_proxy_tool.py
=> fix issue#537

modelscope_agent/rag/knowledge.py, tests/test_rag.py
=> fix bug about Knowledge filter,fix #540

tests/test_callback.py
skip api test for all forked pr
=> skip api test for all forked pr

modelscope_agent/agent.py
=> fix openapi tool

apps/codexgraph_agent/help.py, apps/codexgraph_agent/pages/components/page.py, modelscope_agent/environment/graph_database/build.py, modelscope_agent/environment/graph_database/indexer/my_client.py
=> add build error msg

apps/agentfabric/server.py, modelscope_agent/agent.py, modelscope_agent/tools/dashscope_tools/paraformer_asr_tool.py, modelscope_agent/tools/dashscope_tools/style_repaint.py, modelscope_agent_servers/tool_node_server/api.py
add fall back when file name contain file path
skip mem init if files were jpeg,png or jpg
=> add fall back when file name input is invalid

modelscope_agent/tools/utils/openapi_utils.py
=> support none operationId

modelscope_agent/agent.py, modelscope_agent/tools/base.py, modelscope_agent/tools/utils/openapi_utils.py
=> Fix the issue with the tool being uncallable.

apps/multi_roles_chat_room/requirements.txt, modelscope_agent/agents/multi_role_play.py
=> add _detect_tool on multi_role_play, fix #614

modelscope_agent/agents/data_science_assistant.py
…mpose_task (#640)
during task decomposition
https://github.com/modelscope/ms-agent/issues/640
=> Fix(DataScienceAssistant): handle CodeCell JSON serialization during task decomposition

modelscope_agent/utils/utils.py
- Modify parse_code() to accept raw JSON text when lang='json'
- Add JSON5 parsing support for more flexible JSON handling"
reference: https://github.com/modelscope/ms-agent/issues/646
fix #646
=> Bug fix handle raw JSON input without markdown fences. (#646)

ms_agent/agent/llm_agent.py, ms_agent/cli/run.py, ms_agent/llm/openai_llm.py, ms_agent/llm/utils.py, ms_agent/workflow/base.py, ms_agent/workflow/chain_workflow.py, tests/llm/test_openai.py
=> add llm tokens

ms_agent/tools/tool_manager.py
=> fix: Handle multi-layer escaped JSON string from model output

ms_agent/utils/utils.py
=> Mcp agent v1 3 add get_default_config

modelscope_agent/schemas.py
=> fix: handle missing is_success field in Task.reset(). (#670)

.dev_scripts/dockerci.sh, .github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/feature-requests.yaml, .github/PULL_REQUEST_TEMPLATE.md
=> Simplify issue and PR template

ms_agent/tools/docling/doc_loader.py, ms_agent/utils/utils.py, ms_agent/workflow/research_workflow.py
1. Support for txt processing in workflow.
2. Support for file preprocessing to filter inaccessible files and those exceeding the size limit.
3. Support for converting txt to html to meet Docling's requirements (Can be used for subsequent extraction of heading chunks).
4. Fix the logic issue in URL validation.
=> Support for txt processing and file preprocessing

ms_agent/callbacks/input_callback.py
Fix input_callback will cause another assistant round
=> fix input_callback

ms_agent/tools/mcp_client.py
=> fix mcp type matching

.github/workflows/citest.yaml
=> udpate runner

ms_agent/agent/llm_agent.py, ms_agent/llm/openai_llm.py, ms_agent/tools/tool_manager.py, projects/code_scratch/architecture.yaml, projects/code_scratch/callbacks/artifact_callback.py, projects/code_scratch/callbacks/coding_callback.py, projects/code_scratch/coding.yaml, projects/code_scratch/refine.yaml
=> Fix some compatible bugs

README.md
=> feat: update readme for code scratch

README.md
=> feat: update readme for memory
